title: "SIALOU Koffi Rodrigue"
logo: img/photoSIALOU.jpg
description: "DevOps | Alphabétiseur Numérique"
lang: fr

# Thème choisi
# theme: jekyll-theme-minimal
# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
# theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine

# Options du thème
show_downloads: true
google_analytics: UA-XXXXXXXXX-X   # (remplace si tu veux suivre les visites avec Google Analytics, sinon supprime)

# Liens de navigation (affichés comme menu ou boutons selon le thème)
social_links:
  email: "sialousialou@gmail.com"
  linkedin: "https://linkedin.com/in/sia-rodrigue"
  github: "https://github.com/SialouWebServices"
  twitter: "https://twitter.com/sialousialou"
  facebook: "https://facebook.com/sialousialou"
  instagram: "https://instagram.com/sialous"

# Personnalisation SEO (métadonnées)
author: "SIALOU Koffi Rodrigue"
keywords: "alphabétisation numérique, DevOps, RIAN, Côte d'Ivoire, transformation digitale"
timezone: "Africa/Abidjan"

# Footer personnalisé
footer: "© 2025 SIALOU Koffi Rodrigue — Portfolio GitHub Pages"
