title: "SIALOU Koffi Rodrigue"
logo: img/photoSIALOU.jpg
description: "Responsable d'organisation du Réseau Ivoirien des Alphabétiseurs Numériques - RIAN"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
